services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: capstone_postgres
    environment:
      POSTGRES_DB: capstone_db
      POSTGRES_USER: capstone_user
      POSTGRES_PASSWORD: capstone_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
